import {
    IconBooks,
    IconBrain,
    IconCoffee,
    IconCompass,
    IconFileText,
    IconFlame,
    IconFlower,
    IconGenderTransgender,
    IconGhost,
    IconHeart,
    IconHearts,
    IconHourglass,
    IconMan,
    IconMasksTheater,
    IconMoodSad,
    IconMoodSmile,
    IconMoon,
    IconRobot,
    IconRocket,
    IconSchool,
    IconSearch,
    IconSparkles,
    IconSwords,
    IconTarget,
    IconTrophy,
    IconUsersGroup,
    IconWand,
    IconWoman
} from '@tabler/icons-react';
import {I18N} from "../components/I18N.tsx";
import type {ReactNode} from "react";

export const GENRE_ORDINALS = {
    ACTION: '0',
    ADULT: '1',
    ADVENTURE: '2',
    COMEDY: '3',
    DOUJINSHI: '4',
    DRAMA: '5',
    ECCHI: '6',
    FANTASY: '7',
    GENDERBENDER: '8',
    HAREM: '9',
    HISTORICAL: '10',
    HORROR: '11',
    JOSEI: '12',
    MAGIC: '13',
    MARTIALARTS: '14',
    MECHA: '15',
    MYSTERY: '16',
    ONESHOT: '17',
    PSYCHOLOGICAL: '18',
    ROMANCE: '19',
    SCHOOLLIFE: '20',
    SCIFI: '21',
    SEINEN: '22',
    SHOUJO: '23',
    SHOUJOAI: '24',
    SHOUNEN: '25',
    SHOUNENAI: '26',
    SLICEOFLIFE: '27',
    SPORTS: '28',
    SUPERNATURAL: '29',
    TRAGEDY: '30',
    YAOI: '31',
    YURI: '32',
} as const;

export type GenreOrdinalStr = typeof GENRE_ORDINALS[keyof typeof GENRE_ORDINALS];

// eslint-disable-next-line react-refresh/only-export-components
export const BOOK_GENRE_CONFIG: Record<GenreOrdinalStr, {
    label: ReactNode;
    color: string;
    icon: React.FC<any>
}> = {
    [GENRE_ORDINALS.ACTION]: {label: <I18N>genre_action</I18N>, color: 'red', icon: IconSwords},
    [GENRE_ORDINALS.ADULT]: {label: <I18N>genre_adult</I18N>, color: 'red', icon: IconFlame},
    [GENRE_ORDINALS.ADVENTURE]: {label: <I18N>genre_adventure</I18N>, color: 'green', icon: IconCompass},
    [GENRE_ORDINALS.COMEDY]: {label: <I18N>genre_comedy</I18N>, color: 'yellow', icon: IconMoodSmile},
    [GENRE_ORDINALS.DOUJINSHI]: {label: <I18N>genre_doujinshi</I18N>, color: 'violet', icon: IconBooks},
    [GENRE_ORDINALS.DRAMA]: {label: <I18N>genre_drama</I18N>, color: 'indigo', icon: IconMasksTheater},
    [GENRE_ORDINALS.ECCHI]: {label: <I18N>genre_ecchi</I18N>, color: 'pink', icon: IconFlame},
    [GENRE_ORDINALS.FANTASY]: {label: <I18N>genre_fantasy</I18N>, color: 'violet', icon: IconWand},
    [GENRE_ORDINALS.GENDERBENDER]: {label: <I18N>genre_gender_bender</I18N>, color: 'pink', icon: IconGenderTransgender},
    [GENRE_ORDINALS.HAREM]: {label: <I18N>genre_harem</I18N>, color: 'pink', icon: IconUsersGroup},
    [GENRE_ORDINALS.HISTORICAL]: {label: <I18N>genre_historical</I18N>, color: 'yellow', icon: IconHourglass},
    [GENRE_ORDINALS.HORROR]: {label: <I18N>genre_horror</I18N>, color: 'gray', icon: IconGhost},
    [GENRE_ORDINALS.JOSEI]: {label: <I18N>genre_josei</I18N>, color: 'pink', icon: IconWoman},
    [GENRE_ORDINALS.MAGIC]: {label: <I18N>genre_magic</I18N>, color: 'violet', icon: IconSparkles},
    [GENRE_ORDINALS.MARTIALARTS]: {label: <I18N>genre_martial_arts</I18N>, color: 'orange', icon: IconTarget},
    [GENRE_ORDINALS.MECHA]: {label: <I18N>genre_mecha</I18N>, color: 'gray', icon: IconRobot},
    [GENRE_ORDINALS.MYSTERY]: {label: <I18N>genre_mystery</I18N>, color: 'indigo', icon: IconSearch},
    [GENRE_ORDINALS.ONESHOT]: {label: <I18N>genre_oneshot</I18N>, color: 'teal', icon: IconFileText},
    [GENRE_ORDINALS.PSYCHOLOGICAL]: {label: <I18N>genre_psychological</I18N>, color: 'indigo', icon: IconBrain},
    [GENRE_ORDINALS.ROMANCE]: {label: <I18N>genre_romance</I18N>, color: 'pink', icon: IconHeart},
    [GENRE_ORDINALS.SCHOOLLIFE]: {label: <I18N>genre_school_life</I18N>, color: 'blue', icon: IconSchool},
    [GENRE_ORDINALS.SCIFI]: {label: <I18N>genre_sci_fi</I18N>, color: 'cyan', icon: IconRocket},
    [GENRE_ORDINALS.SEINEN]: {label: <I18N>genre_seinen</I18N>, color: 'blue', icon: IconMan},
    [GENRE_ORDINALS.SHOUJO]: {label: <I18N>genre_shoujo</I18N>, color: 'pink', icon: IconFlower},
    [GENRE_ORDINALS.SHOUJOAI]: {label: <I18N>genre_shoujo_ai</I18N>, color: 'pink', icon: IconHearts},
    [GENRE_ORDINALS.SHOUNEN]: {label: <I18N>genre_shounen</I18N>, color: 'orange', icon: IconFlame},
    [GENRE_ORDINALS.SHOUNENAI]: {label: <I18N>genre_shounen_ai</I18N>, color: 'indigo', icon: IconHearts},
    [GENRE_ORDINALS.SLICEOFLIFE]: {label: <I18N>genre_slice_of_life</I18N>, color: 'green', icon: IconCoffee},
    [GENRE_ORDINALS.SPORTS]: {label: <I18N>genre_sports</I18N>, color: 'orange', icon: IconTrophy},
    [GENRE_ORDINALS.SUPERNATURAL]: {label: <I18N>genre_supernatural</I18N>, color: 'violet', icon: IconMoon},
    [GENRE_ORDINALS.TRAGEDY]: {label: <I18N>genre_tragedy</I18N>, color: 'gray', icon: IconMoodSad},
    [GENRE_ORDINALS.YAOI]: {label: <I18N>genre_yaoi</I18N>, color: 'indigo', icon: IconHeart},
    [GENRE_ORDINALS.YURI]: {label: <I18N>genre_yuri</I18N>, color: 'pink', icon: IconHeart},
};